---
# tasks file for dj-wasabi.zabbix-agent

- name: "Fix facts for linuxmint - distribution release"
  set_fact:
    zabbix_agent_distribution_release: xenial
  when:
    - ansible_os_family == "Linuxmint"
    - ansible_distribution_release == "sonya" or ansible_distribution_release == "serena"

- name: "Fix facts for linuxmint - family"
  set_fact:
    zabbix_agent_os_family: Debian
  when:
    - ansible_os_family == "Linuxmint"

- name: "Include OS-specific variables"
  include_vars: "{{ zabbix_agent_os_family }}.yml"
  tags:
    - vars
    - zabbix-agent

- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - zabbix_agent_os_family == "RedHat"
    - not (zabbix_agent_docker | bool)
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - zabbix_agent_os_family == "Sangoma"
    - not (zabbix_agent_docker | bool)
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install the correct repository"
  include: "Debian.yml"
  when:
    - zabbix_agent_os_family == "Debian"
    - not (zabbix_agent_docker | bool)
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install the correct repository"
  include: "Suse.yml"
  when:
    - zabbix_agent_os_family == "Suse"
    - not (zabbix_agent_docker | bool)
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install local python-netaddr package"
  pip:
    name: netaddr
    state: present
  register: zabbix_python_netaddr_package_installed
  until: zabbix_python_netaddr_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_agent_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages | bool
    - ansible_all_ipv4_addresses is defined or (zabbix_agent_ip is not defined and total_private_ip_addresses is defined)

- name: "Encrypt with TLS PSK auto management"
  include_tasks: tlspsk_auto.yml
  when:
    - zabbix_agent_tlspsk_auto | bool
    - (zabbix_agent_tlspskfile is undefined) or (zabbix_agent_tlspskfile | length == '0')
    - (zabbix_agent_tlspsk_secret is undefined) or (zabbix_agent_tlspsk_secret | length == '0')

- name: "Install the correct repository"
  include: Windows.yml
  when:
    - zabbix_agent_os_family == "Windows"

- name: "Install the correct repository"
  include: Linux.yml
  when:
    - (zabbix_agent_os_family != "Windows") or (zabbix_agent_docker | bool)

- name: "Installing the Zabbix-api package on localhost"
  pip:
    name: zabbix-api
    state: present
  register: zabbix_api_package_installed
  until: zabbix_api_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_agent_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages | bool
    - (zabbix_api_create_hostgroup | bool) or (zabbix_api_create_hosts | bool)

- name: "Create hostgroups"
  zabbix_group:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_group: "{{ zabbix_host_groups }}"
    state: "{{ zabbix_create_hostgroup }}"
    validate_certs: "{{ zabbix_validate_certs|default(omit) }}"
  when:
    - zabbix_api_create_hostgroup | bool
  delegate_to: localhost
  become: no
  tags:
    - api

- name: "Create a new host or update an existing host's info"
  zabbix_host:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ zabbix_agent_hostname }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ zabbix_link_templates }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    force: "{{ zabbix_update_host }}"
    proxy: "{{ zabbix_proxy }}"
    inventory_mode: "{{ zabbix_inventory_mode }}"
    interfaces: "{{ zabbix_agent_interfaces }}"
    visible_name: "{{ zabbix_visible_hostname|default(zabbix_agent_hostname) }}"
    tls_psk: "{{ zabbix_agent_tlspsk_secret|default(omit) }}"
    tls_psk_identity: "{{ zabbix_agent_tlspskidentity|default(omit) }}"
    tls_issuer: "{{ zabbix_agent_tlsservercertissuer|default(omit) }}"
    tls_subject: "{{ zabbix_agent_tlsservercertsubject|default(omit) }}"
    tls_accept: "{{ zabbix_agent_tls_config[zabbix_agent_tlsaccept if zabbix_agent_tlsaccept else 'unencrypted'] }}"
    tls_connect: "{{ zabbix_agent_tls_config[zabbix_agent_tlsconnect if zabbix_agent_tlsconnect else 'unencrypted'] }}"
    validate_certs: "{{ zabbix_validate_certs|default(omit) }}"
  when:
    - zabbix_api_create_hosts | bool
  delegate_to: localhost
  become: no
  changed_when: false
  tags:
    - api

- name: "Updating host configuration with macros"
  zabbix_hostmacro:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ zabbix_agent_hostname }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
    validate_certs: "{{ zabbix_validate_certs|default(omit) }}"
  with_items: "{{ zabbix_macros | default([]) }}"
  when:
    - zabbix_api_create_hosts | bool
    - zabbix_macros is defined
    - item.macro_key is defined
  delegate_to: localhost
  become: no
  tags:
    - api

- name: "Including userparameters"
  include: "userparameter.yml"
  when: zabbix_agent_userparameters|length > 0
  tags:
    - zabbix-agent
    - userparameter
