---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
      zabbix_agent: zabbix-agent
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Set short version name"
  set_fact:
      zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Use EPEL package name"
  set_fact:
      zabbix_agent_package: "zabbix{{ zabbix_short_version }}-agent"
  when: zabbix_repo == "epel"
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Install basic repo file"
  template: src=rhel.repo.j2
            dest=/etc/yum.repos.d/zabbix.repo
            owner=root
            group=root
            mode=0644
  when: zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init
    - config

- name: "RedHat | Installing zabbix-agent"
  yum:  pkg={{ zabbix_agent_package }}
        state={{ zabbix_agent_package_state }}
  sudo: yes
  tags:
    - init
    - zabbix-agent

- name: "RedHat | Enable the service"
  service: name={{ zabbix_agent_service }}
           enabled=yes
  sudo: yes
  tags:
    - zabbix-agent
    - init
    - service

