---

- name: "Windows | Set default architecture"
  set_fact:
    windows_arch: 32

- name: "Windows | Set path to zabbix.exe"
  set_fact:
    zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\win{{ windows_arch }}\zabbix_agentd.exe'

- name: "Windows | Set variables specific to Zabbix 4.0"
  set_fact:
    zabbix_win_package: zabbix_agents-{{ zabbix_version_long }}-win-amd64.zip
    zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agentd.exe'
  when:
    - zabbix_version_long is version('4.0.0', '>=')

- name: "Windows | Override architecture if 64-bit"
  set_fact:
    windows_arch: 64
  when:
    - ansible_architecture == "64-bit"

- name: "Windows | Create directory structure"
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ zabbix_win_install_dir }}"
    - "{{ zabbix_agent_win_include }}"

- name: "Windows | Check if file is already downloaded"
  win_stat:
    path: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
  register: file_info

- name: "Windows | Download Zabbix Agent Zip file"
  win_get_url:
    url: "{{ zabbix_win_download_link }}"
    dest: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
    force: False

- name: "Windows | Unzip file"
  win_unzip:
    src: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
    dest: "{{ zabbix_win_install_dir }}"
    creates: '{{ zabbix_win_exe_path }}'

- name: "Windows | Configure zabbix-agent"
  win_template:
    src: zabbix_agentd.conf.j2
    dest: '{{ zabbix_win_install_dir }}\zabbix_agentd.conf'
  notify: restart win zabbix agent

- name: "Windows | Register Service"
  win_command: '{{ zabbix_win_exe_path }} --config {{ zabbix_win_install_dir }}\zabbix_agentd.conf --install'
  register: zabbix_windows_install
  args:
    creates: '{{ zabbix_win_install_dir }}\.installed'

- name: "Windows | Create done file so it won't register itself again"
  win_file:
    path: '{{ zabbix_win_install_dir }}\.installed'
    state: touch
  when: zabbix_windows_install is changed

- name: "Windows | Set service startup mode to auto and ensure it is started"
  win_service:
    name: Zabbix Agent
    start_mode: auto
    state: started

- name: "Windows | Firewall rule"
  win_firewall_rule:
    name: Zabbix Agent
    localport: "{{ zabbix_agent_listenport }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
