---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Installing packages on CentOS family"
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - net-tools
        - which
      when: ansible_os_family == 'RedHat'
    - name: "Installing packages on Debian family"
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - net-tools
      when: ansible_os_family == 'Debian'
    - name: "Installing packages on Suse family"
      shell: zypper install -y python-xml python-libxml2 net-tools which
      changed_when: False
      when: ansible_os_family == 'Suse'
      tags:
        - skip_ansible_lint

  roles:
    - role: ansible-zabbix-agent
      zabbix_agent_server: 192.168.3.33
      zabbix_agent_serveractive: 192.168.3.33
      zabbix_agent_listenip: 0.0.0.0
      zabbix_agent_tlsconnect: psk
      zabbix_agent_tlsaccept: psk
      zabbix_agent_tlspskidentity: my_Identity
      zabbix_agent_tlspskfile: /data/certs/zabbix.psk
      zabbix_agent_tlspsk_secret: 97defd6bd126d5ba7fa5f296595f82eac905d5eda270207a580ab7c0cb9e8eab
